### ISSUE TITLE
Errors in directions in README.md

### ISSUE THREAD

**Issue by madaalch** [anoduck/Biber-OpenBSD#2]
Please update the instructions here to reflect available packages.
Please also clarify `bibtex`. I removed it from the list when executing the command and it seems like there are no issues with the build, so it may be a random mistake?

"# Then install the remainder of the dependencies needed for the build.
`cpm install -g bibtex Readonly::XS Pod::Simple Pod::Simple::TranscodeSmart \
Pod::Simple::TranscodeDumb pod::PerlDoc Text::BibTex Text::CSV`"

- `Text::BibTex` to `Text::BibTeX` (uppercase X)
- `pod:PerlDoc` to `Pod:Perldoc` (Uppercase P in Pod and lowecase d in Doc)

**Comment by anoduck** [comment]
Done.
